# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_txt_plain_text_2(object):
    def setupUi(self, txt_plain_text_2):
        txt_plain_text_2.setObjectName("txt_plain_text_2")
        txt_plain_text_2.resize(917, 615)
        self.centralwidget = QtWidgets.QWidget(txt_plain_text_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 20, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 80, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 230, 61, 16))
        self.label_5.setObjectName("label_5")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(70, 70, 381, 101))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(540, 70, 351, 101))
        self.txt_info.setObjectName("txt_info")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(70, 240, 381, 121))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(520, 230, 361, 131))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(530, 30, 131, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(70, 430, 101, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(360, 430, 101, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(520, 430, 141, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(800, 430, 91, 23))
        self.btn_verify.setObjectName("btn_verify")
        txt_plain_text_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(txt_plain_text_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 22))
        self.menubar.setObjectName("menubar")
        txt_plain_text_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(txt_plain_text_2)
        self.statusbar.setObjectName("statusbar")
        txt_plain_text_2.setStatusBar(self.statusbar)

        self.retranslateUi(txt_plain_text_2)
        QtCore.QMetaObject.connectSlotsByName(txt_plain_text_2)

    def retranslateUi(self, txt_plain_text_2):
        _translate = QtCore.QCoreApplication.translate
        txt_plain_text_2.setWindowTitle(_translate("txt_plain_text_2", "MainWindow"))
        self.label.setText(_translate("txt_plain_text_2", "RSA CIPHER"))
        self.label_2.setText(_translate("txt_plain_text_2", "Plain Text:"))
        self.label_3.setText(_translate("txt_plain_text_2", "CipherText:"))
        self.label_4.setText(_translate("txt_plain_text_2", "Information:"))
        self.label_5.setText(_translate("txt_plain_text_2", "Signature:"))
        self.btn_gen_keys.setText(_translate("txt_plain_text_2", "Generate Keys"))
        self.btn_encrypt.setText(_translate("txt_plain_text_2", "Encrypt"))
        self.btn_decrypt.setText(_translate("txt_plain_text_2", "Decrypy"))
        self.btn_sign.setText(_translate("txt_plain_text_2", "Sign"))
        self.btn_verify.setText(_translate("txt_plain_text_2", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    txt_plain_text_2 = QtWidgets.QMainWindow()
    ui = Ui_txt_plain_text_2()
    ui.setupUi(txt_plain_text_2)
    txt_plain_text_2.show()
    sys.exit(app.exec_())
